local script_path = arg and arg[0] or debug.getinfo(1, "S").source:sub(2)
local nvim_root = script_path:gsub("/scripts/update_dashboard_patterns%.lua$", "")
local input_path = nvim_root .. "/assets/dashboard/patterns.txt"
local output_path = nvim_root .. "/lua/config/dashboard_pattern_options.lua"

local function read_file(path)
  local file = assert(io.open(path, "rb"))
  local text = file:read("*a")
  file:close()
  return text
end

local function write_file(path, text)
  local file = assert(io.open(path, "wb"))
  file:write(text)
  file:close()
end

local function split_lines(text)
  text = text:gsub("\r\n", "\n"):gsub("\r", "\n")
  if text:sub(-1) ~= "\n" then
    text = text .. "\n"
  end

  local lines = {}
  for line in text:gmatch("([^\n]*)\n") do
    lines[#lines + 1] = line
  end
  return lines
end

local function trim(line)
  return line:match("^%s*(.-)%s*$")
end

local function finish_chunk(chunks, current, first_line, last_line)
  while current[1] == "" do
    table.remove(current, 1)
    first_line = first_line + 1
  end
  while current[#current] == "" do
    table.remove(current)
    last_line = last_line - 1
  end
  if #current > 0 then
    chunks[#chunks + 1] = {
      lines = current,
      first_line = first_line,
      last_line = last_line,
    }
  end
end

local function split_chunks(lines)
  local start_at = 1
  if lines[1] and trim(lines[1]) == "fractals" and lines[2] == "" then
    start_at = 3
  end

  local chunks = {}
  local current = {}
  local current_start = nil
  local current_end = nil
  local blank_count = 0

  for line_number = start_at, #lines do
    local line = lines[line_number]
    if line == "" then
      blank_count = blank_count + 1
    else
      if blank_count >= 2 and current_start then
        finish_chunk(chunks, current, current_start, current_end)
        current = {}
        current_start = nil
        current_end = nil
      elseif blank_count == 1 and current_start then
        current[#current + 1] = ""
      end

      blank_count = 0
      current_start = current_start or line_number
      current_end = line_number
      current[#current + 1] = line
    end
  end

  if current_start then
    finish_chunk(chunks, current, current_start, current_end)
  end

  return chunks
end

local function long_quote(text)
  local equals = ""
  while text:find("]" .. equals .. "]", 1, true) do
    equals = equals .. "="
  end
  return "[" .. equals .. "[" .. text .. "]" .. equals .. "]"
end

local lines = split_lines(read_file(input_path))
local chunks = split_chunks(lines)
local out = {}

out[#out + 1] = "-- Generated by .config/nvim/scripts/update_dashboard_patterns.lua."
out[#out + 1] = "-- Source art is pulled verbatim into .config/nvim/assets/dashboard/patterns.txt."
out[#out + 1] = "-- Keep this as a plain list of raw ASCII strings; metadata is derived at runtime."
out[#out + 1] = "return {"

for _, chunk in ipairs(chunks) do
  local art = table.concat(chunk.lines, "\n")
  out[#out + 1] = "  " .. long_quote(art) .. ","
end

out[#out + 1] = "}"
out[#out + 1] = ""

write_file(output_path, table.concat(out, "\n"))
print(("generated %d dashboard pattern options -> %s"):format(#chunks, output_path))
