#!/usr/bin/env bash
# TODO:: Pick an outer directory and create a project in it. Git init in the folder

if [[ $# -eq 1 ]]; then
    selected=$1
else
    # Add directories to fzf later
    directories=(
        ~/workspace/
        ~/dotfiles/
        ~/obsidian/
        ~/workspace/reference/
        ~/workspace/open-source/
    )

    for dir in $(find ~/dotfiles/.config -mindepth 1 -maxdepth 1 -type d); do
        directories+=("$dir")
    done

    find_directories_depth_2=(
        ~/workspace
        ~/dotfiles/.local
    )
    for dir in $(find "${find_directories_depth_2[@]}" -mindepth 2 -maxdepth 2 -type d); do
        directories+=("$dir")
    done

    selected=$(printf "%s\n" "${directories[@]}" | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)

if ! tmux has-session -t "=$selected_name" 2>/dev/null; then
    if [[ -z ${TMUX:-} ]]; then
        exec tmux new-session -s "$selected_name" -c "$selected"
    fi

    tmux new-session -ds "$selected_name" -c "$selected"
fi

if [[ -z ${TMUX:-} ]]; then
    exec tmux attach-session -t "=$selected_name"
fi

tmux switch-client -t "=$selected_name"
