#!/usr/bin/env bash

if [[ $# -eq 1 ]]; then
    selected=$1
else
    find_directories=()
    
    hostname=$(hostname)
    case $hostname in
        "AB95544")
            find_directories=(
                ~/workspace/playground
                ~/workspace/reference
                ~/workspace/open-source
                ~/dotfiles/.config
                ~/workspace/runway
                ~/workspace/docwf
                ~/workspace/SARS
                ~/workspace/datastage
                ~/workspace/poc
                ~/workspace/projects
                ~/workspace/SyssecLab/darpa
                ~/workspace/SyssecLab/differential-privacy
            )
            ;;
        *)
            echo "Machine not recognized"
            ;;
    esac
    find_output=$(find "${find_directories[@]}" -mindepth 1 -maxdepth 1 -type d)

    # Append find results into directories
    directories=(~/workspace/ ~/dotfiles)
    while IFS= read -r dir; do
      directories+=("$dir")
    done <<< "$find_output"

    selected=$(printf "%s\n" "${directories[@]}" | fzf)
fi

if [[ -z $selected ]]; then
    exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
    tmux new-session -s $selected_name -c $selected
    exit 0
fi

if ! tmux has-session -t=$selected_name 2> /dev/null; then
    tmux new-session -ds $selected_name -c $selected
fi

tmux switch-client -t $selected_name
