#!/opt/homebrew/bin/bash
# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"
FONT="Hack Nerd Font"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

bar=(
    --bar
    position=top
    height=30
    color=0x00000000
)
sketchybar "${bar[@]}"

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
  padding_left=5
  padding_right=5
  icon.font="$FONT:Regular:14.0"
  label.font="$FONT:Regular:14.0"
  icon.color=0xffffffff
  label.color=0xffffffff
  icon.padding_left=4
  icon.padding_right=4
  label.padding_left=4
  label.padding_right=4
)
sketchybar --default "${default[@]}"

# Left
source $ITEM_DIR/aerospace.sh

battery=(
    --add
        item
        battery
        right
    --set
        battery
        update_freq=120
        script="$PLUGIN_DIR/battery.sh"
        font.style="Regular"
    --subscribe battery
        system_woke
        power_source_change
)
# Right items
source $ITEM_DIR/clock.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/network.sh

# Auto reload
sketchybar --hotload true

##### Force all scripts to run the first time (never do this in a script) #####
sketchybar --update
